"""Curated dataset: 80+ cultural holidays + signature dishes.

Each entry's `date` is "MM-DD" (fixed) or "WEEK:..." for movable feasts.
Keep the Python-literal form so we get IDE introspection.
"""

from __future__ import annotations
from dataclasses import dataclass
from typing import Literal

Difficulty = Literal["home", "store", "specialty"]
DIFFICULTY_LABEL = {
    "home": "🏠 自宅で作りやすい",
    "store": "🏪 近所のスーパー / 持ち帰り",
    "specialty": "🌐 専門店または個人輸入",
}


@dataclass(frozen=True)
class Holiday:
    id: str
    date: str  # "MM-DD" only (movable feasts approximated to nearest fixed date)
    country_jp: str
    country_flag: str
    holiday_jp: str
    holiday_en: str
    dish_jp: str
    dish_native: str
    where: Difficulty
    blurb: str


HOLIDAYS: tuple[Holiday, ...] = (
    Holiday("nyd-jp", "01-01", "日本", "🇯🇵", "元日", "Shogatsu",
            "お雑煮", "ozōni", "home",
            "お餅とお出汁、青菜、紅白の具材で新年を迎える"),
    Holiday("epiphany-es", "01-06", "スペイン", "🇪🇸", "公現祭", "Día de Reyes",
            "ロスコン・デ・レイエス", "Roscón de Reyes", "store",
            "ドライフルーツを乗せたリング型菓子パン。中に小さな人形を隠す"),
    Holiday("burns-uk", "01-25", "スコットランド", "🏴󠁧󠁢󠁳󠁣󠁴󠁿", "バーンズ・ナイト", "Burns Night",
            "ハギス", "haggis", "specialty",
            "羊の内臓・オーツ麦をプディング状にした、詩人ロバート・バーンズを讃える伝統食"),
    Holiday("oshogatsu-mochi", "01-11", "日本", "🇯🇵", "鏡開き", "Kagami-biraki",
            "おしるこ", "oshiruko", "home",
            "鏡餅を割って小豆汁粉でいただく"),
    Holiday("lunar-cn", "02-10", "中国", "🇨🇳", "春節", "Spring Festival",
            "餃子", "jiaozi", "home",
            "金塊に見立てた水餃子を家族で包む"),
    Holiday("setsubun-jp", "02-03", "日本", "🇯🇵", "節分", "Setsubun",
            "恵方巻", "ehōmaki", "store",
            "その年の恵方を向き、丸かじりで黙って食べる太巻き"),
    Holiday("valentine", "02-14", "世界", "💝", "バレンタインデー", "Valentine's Day",
            "ガトーショコラ", "gâteau au chocolat", "home",
            "贈り物の定番、濃厚チョコレートケーキ"),
    Holiday("st-david-wales", "03-01", "ウェールズ", "🏴󠁧󠁢󠁷󠁬󠁳󠁿", "聖デイビッドの日", "St David's Day",
            "カウル", "cawl", "home",
            "ラム肉と根菜のあたたかいシチュー"),
    Holiday("hina-jp", "03-03", "日本", "🇯🇵", "ひな祭り", "Hinamatsuri",
            "ちらし寿司", "chirashizushi", "home",
            "桃の節句に女の子の健やかな成長を願う彩り寿司"),
    Holiday("holi-in", "03-17", "インド", "🇮🇳", "ホーリー祭", "Holi",
            "グジヤ", "gujiya", "specialty",
            "ココナッツとカルダモンを詰めた揚げ菓子。色粉まつりの定番"),
    Holiday("stpatricks-ie", "03-17", "アイルランド", "🇮🇪", "聖パトリックの日", "St Patrick's Day",
            "アイリッシュシチュー", "Irish stew", "home",
            "羊肉・じゃがいも・玉ねぎを煮込む、シンプルな家庭料理"),
    Holiday("nowruz-ir", "03-21", "イラン", "🇮🇷", "ノウルーズ", "Nowruz",
            "サブズィー・ポロウ", "sabzi polo", "specialty",
            "ハーブ入りのご飯と焼き魚で春分を祝う"),
    Holiday("hanami-jp", "03-28", "日本", "🇯🇵", "お花見", "Hanami",
            "三色団子", "sanshoku-dango", "store",
            "桜の下で食べる、桜・白・蓬の三色団子"),
    Holiday("songkran-th", "04-13", "タイ", "🇹🇭", "ソンクラーン", "Songkran",
            "カオチェー", "khao chae", "specialty",
            "氷水ご飯。ジャスミンの香りの冷たいお米と漬物・揚げ物の数皿"),
    Holiday("easter", "04-12", "ヨーロッパ", "✝️", "復活祭", "Easter",
            "ホットクロスバンズ", "hot cross buns", "store",
            "シナモンとレーズンの十字パン。聖金曜日の朝の定番"),
    Holiday("greekeaster", "04-19", "ギリシャ", "🇬🇷", "ギリシャ正教復活祭", "Pascha",
            "マギリッツァ", "magiritsa", "specialty",
            "羊の内臓と卵レモンスープで断食明けを祝う"),
    Holiday("anzac", "04-25", "オーストラリア", "🇦🇺", "アンザックデー", "ANZAC Day",
            "アンザックビスケット", "ANZAC biscuit", "home",
            "オーツ・ココナッツの素朴な焼き菓子。戦没者を偲ぶ"),
    Holiday("showa", "04-29", "日本", "🇯🇵", "昭和の日", "Showa Day",
            "ナポリタン", "naporitan", "store",
            "昭和の喫茶店を彷彿とさせるケチャップスパゲッティ"),
    Holiday("kmd-jp", "05-05", "日本", "🇯🇵", "こどもの日", "Children's Day",
            "柏餅", "kashiwa-mochi", "store",
            "柏の葉に包まれた小豆あんの和菓子"),
    Holiday("cinco-de-mayo", "05-05", "メキシコ", "🇲🇽", "シンコ・デ・マヨ", "Cinco de Mayo",
            "モレ・ポブラーノ", "mole poblano", "specialty",
            "チョコとチリで煮込んだ濃厚ソース。鶏肉と共に"),
    Holiday("vesakha", "05-12", "スリランカ", "🇱🇰", "ウェーサーカ祭", "Vesak",
            "キリバット", "kiribath", "home",
            "ココナッツミルクで炊いたお米。仏陀の生誕・成道・涅槃を祝う"),
    Holiday("syttende-no", "05-17", "ノルウェー", "🇳🇴", "ノルウェー憲法記念日", "Syttende Mai",
            "ホットドッグ・イ・ロンペ", "Pølse i lompe", "home",
            "ふんわりした薄焼きパンに茹でソーセージを巻く、当日の屋台の定番"),
    Holiday("vict-canada", "05-19", "カナダ", "🇨🇦", "ヴィクトリア・デー", "Victoria Day",
            "バタータルト", "butter tart", "home",
            "メープルバター・カスタードのタルト。Long Weekend のお供"),
    Holiday("dragonboat", "05-20", "中国", "🇨🇳", "端午節", "Duanwu",
            "ちまき", "zòngzi", "store",
            "笹の葉に包んだ蒸し餅米。屈原を偲ぶ"),
    Holiday("rodaal", "05-23", "ベルギー", "🇧🇪", "ローダル祭", "Hanswijk Procession",
            "ベルギーワッフル", "Liège waffle", "store",
            "焦がし糖の甘いポケット入りワッフル"),
    Holiday("memorial-us", "05-26", "アメリカ", "🇺🇸", "メモリアルデー", "Memorial Day",
            "バーベキューブリスケット", "BBQ brisket", "specialty",
            "夏の幕開けを告げる、長時間燻製ビーフ"),
    Holiday("nat-day-ch", "08-01", "スイス", "🇨🇭", "スイス建国記念日", "Bundesfeier",
            "ラクレット", "raclette", "specialty",
            "溶かしたチーズをジャガイモにかける。屋外パーティーの定番"),
    Holiday("hari-merdeka", "08-31", "マレーシア", "🇲🇾", "ムルデカ・デー", "Hari Merdeka",
            "ナシレマ", "nasi lemak", "store",
            "ココナッツミルクで炊いたお米、サンバル、煮卵の朝食定番"),
    Holiday("ferrag-it", "08-15", "イタリア", "🇮🇹", "フェラゴスト", "Ferragosto",
            "メロンと生ハム", "prosciutto e melone", "store",
            "真夏の海辺の前菜の定番"),
    Holiday("obon", "08-15", "日本", "🇯🇵", "お盆", "Obon",
            "精進揚げ", "shōjin tempura", "home",
            "野菜だけの天ぷら。先祖を迎える精進料理"),
    Holiday("midsummer-se", "06-21", "スウェーデン", "🇸🇪", "夏至祭", "Midsommar",
            "ニシンの酢漬け", "sill", "specialty",
            "新じゃがイモ・ディル・サワークリームとともに"),
    Holiday("bastille-fr", "07-14", "フランス", "🇫🇷", "革命記念日", "Bastille Day",
            "ラタトゥイユ", "ratatouille", "home",
            "夏野菜のオリーブ油煮込み。プロヴァンスの味"),
    Holiday("oktober-de", "09-21", "ドイツ", "🇩🇪", "オクトーバーフェスト開幕", "Oktoberfest",
            "ブレッツェル", "Brezel", "store",
            "塩を散らした巻きパン。バヴァリアの祭の定番"),
    Holiday("midautumn-cn", "09-17", "中国", "🇨🇳", "中秋節", "Mid-Autumn Festival",
            "月餅", "mooncake", "store",
            "蓮の実・卵黄を詰めた円型菓子。家族で分け合う"),
    Holiday("chuseok-kr", "09-17", "韓国", "🇰🇷", "秋夕", "Chuseok",
            "ソンピョン", "songpyeon", "store",
            "半月形の蒸し餅。胡麻・あんを詰める"),
    Holiday("rosh-il", "09-22", "イスラエル", "🇮🇱", "ユダヤ新年", "Rosh Hashanah",
            "リンゴと蜂蜜", "apples and honey", "home",
            "甘い 1 年への祈り。リンゴに蜂蜜を浸して食べる"),
    Holiday("oktoberfest-mid", "10-03", "ドイツ", "🇩🇪", "ドイツ統一の日", "Tag der Deutschen Einheit",
            "シュニッツェル", "Schnitzel", "store",
            "薄切り肉のカツレツ。レモンを絞って"),
    Holiday("thanksgiving-ca", "10-13", "カナダ", "🇨🇦", "感謝祭", "Thanksgiving (CA)",
            "ローストターキー", "roast turkey", "specialty",
            "クランベリーソースとマッシュドポテトを添えて"),
    Holiday("diwali", "11-01", "インド", "🇮🇳", "ディワーリー", "Diwali",
            "サモサ", "samosa", "store",
            "じゃがいもとスパイスの三角揚げパイ。光の祭典に欠かせない"),
    Holiday("guyfawkes-uk", "11-05", "イギリス", "🇬🇧", "ガイ・フォークス・デー", "Guy Fawkes Night",
            "ファイヤーケーキ", "parkin", "home",
            "オーツ・モラセスのしっとり焼き菓子。焚き火を眺めながら"),
    Holiday("dia-mx", "11-02", "メキシコ", "🇲🇽", "死者の日", "Día de los Muertos",
            "パン・デ・ムエルト", "pan de muerto", "store",
            "オレンジ花水の香る丸パン。お供え物に"),
    Holiday("thanksgiving-us", "11-26", "アメリカ", "🇺🇸", "感謝祭", "Thanksgiving",
            "パンプキンパイ", "pumpkin pie", "home",
            "スパイスとミルクのカスタードパイ"),
    Holiday("xmas-eve-jp", "12-24", "日本", "🇯🇵", "クリスマスイブ", "Christmas Eve (JP)",
            "クリスマスチキン", "fried chicken", "store",
            "日本独特の文化、KFCで予約する家庭も多い"),
    Holiday("xmas-eve-de", "12-24", "ドイツ", "🇩🇪", "クリスマスイブ", "Heiligabend",
            "ジャガイモサラダとソーセージ", "Kartoffelsalat und Würstchen", "home",
            "ドイツの伝統的な質素なイブの夕食"),
    Holiday("xmas-it", "12-24", "イタリア", "🇮🇹", "魚の七料理の夜", "Festa dei sette pesci",
            "バカラ", "baccalà", "specialty",
            "塩漬けタラ。トマトソースで煮込んで"),
    Holiday("toshikoshi", "12-31", "日本", "🇯🇵", "大晦日", "Omisoka",
            "年越しそば", "toshikoshi-soba", "home",
            "細く長く生きる願いを込めて。茹で立てに天かすや海老天"),
    Holiday("hogmanay", "12-31", "スコットランド", "🏴󠁧󠁢󠁳󠁣󠁴󠁿", "ホグマナイ", "Hogmanay",
            "ステーキパイ", "steak pie", "home",
            "牛肉の煮込みをパイ生地で。新年を迎える夕食"),
    Holiday("inde-fr-na", "07-04", "アメリカ", "🇺🇸", "独立記念日", "Independence Day",
            "ホットドッグ", "hot dog", "store",
            "野球場と裏庭バーベキューの夏の味"),
    Holiday("bonalu", "07-20", "インド", "🇮🇳", "ボナル祭", "Bonalu",
            "プラオ", "pulao", "home",
            "サフラン・カルダモンで炊くスパイスご飯"),
    Holiday("oktober-fi", "10-13", "フィンランド", "🇫🇮", "ロイカリ", "Loikari",
            "サーモンスープ", "lohikeitto", "home",
            "クリーミーなサーモンとディルのスープ"),
    Holiday("nat-day-sg", "08-09", "シンガポール", "🇸🇬", "建国記念日", "National Day",
            "チキンライス", "Hainanese chicken rice", "store",
            "茹で鶏とスープで炊いたご飯。屋台の定番"),
    Holiday("nat-day-id", "08-17", "インドネシア", "🇮🇩", "独立記念日", "Hari Merdeka",
            "ナシ・ゴレン", "nasi goreng", "home",
            "ケチャップ・マニスで炒める甘辛炒飯"),
    Holiday("nat-day-mx", "09-16", "メキシコ", "🇲🇽", "独立記念日", "Día de la Independencia",
            "チレ・エン・ノガダ", "chiles en nogada", "specialty",
            "国旗の三色を表した、ナッツソースのピーマン詰め"),
    Holiday("naval-iceland", "06-01", "アイスランド", "🇮🇸", "船員の日", "Sjómannadagurinn",
            "プロッカフィスクル", "plokkfiskur", "home",
            "茹でタラとじゃがいものクリーム煮"),
    Holiday("nat-day-fr-ca", "06-24", "カナダ ケベック", "🇨🇦", "サンジャン・バティスト", "Fête nationale du Québec",
            "プーティン", "poutine", "store",
            "フライドポテトにグレイビーとチーズカード"),
    Holiday("juneteenth-us", "06-19", "アメリカ", "🇺🇸", "ジューンティーンス", "Juneteenth",
            "レッドベルベットケーキ", "red velvet cake", "home",
            "赤い色は黒人の犠牲と祝祭を象徴する"),
    Holiday("hari-raya", "04-10", "マレーシア", "🇲🇾", "ハリ・ラヤ・プアサ", "Hari Raya Aidilfitri",
            "ルンダン", "rendang", "specialty",
            "牛肉のスパイスココナッツ煮込み。断食明けの主役"),
    Holiday("ramadan-iftar", "03-10", "中東", "☪️", "ラマダン (イフタール)", "Ramadan Iftar",
            "デーツ", "khajur", "store",
            "日没後の最初の口に。預言者の習慣に倣う"),
    Holiday("walpurgis-de", "04-30", "ドイツ", "🇩🇪", "ヴァルプルギスの夜", "Walpurgisnacht",
            "ザワークラウト", "Sauerkraut", "store",
            "発酵キャベツとソーセージで春の到来を祝う"),
    Holiday("vappu-fi", "05-01", "フィンランド", "🇫🇮", "ヴァップ", "Vappu",
            "シマ", "sima", "home",
            "レモンと砂糖で発酵させた甘いノンアルコール飲料"),
    Holiday("la-tomatina", "08-26", "スペイン", "🇪🇸", "ラ・トマティーナ", "La Tomatina",
            "ガスパチョ", "gazpacho", "home",
            "完熟トマトの冷製スープ。投げる前に飲む"),
    Holiday("matariki-nz", "07-14", "ニュージーランド", "🇳🇿", "マタリキ", "Matariki",
            "ハンギ", "hāngī", "specialty",
            "地中の蒸し焼き料理。マオリの新年に"),
    Holiday("yam-fest-gh", "08-31", "ガーナ", "🇬🇭", "ホモウォウ祭", "Homowo",
            "ケンキ", "kenkey", "specialty",
            "発酵トウモロコシ粉の蒸し団子。魚と唐辛子ソースで"),
    Holiday("st-georgia-day", "11-23", "ジョージア", "🇬🇪", "ギオルゴバ", "Giorgoba",
            "ハチャプリ", "khachapuri", "specialty",
            "舟形のチーズパン。卵を割り入れる"),
    Holiday("ind-day-india", "08-15", "インド", "🇮🇳", "独立記念日", "Independence Day (IN)",
            "ビリヤニ", "biryani", "store",
            "スパイス米の祝祭料理"),
    Holiday("oktoberfest-aut", "10-26", "オーストリア", "🇦🇹", "国民の日", "Nationalfeiertag",
            "ウィーンナーシュニッツェル", "Wiener Schnitzel", "store",
            "薄切り仔牛肉のカツレツ。レモンで"),
    Holiday("queens-bday-au", "06-08", "オーストラリア", "🇦🇺", "ザ・キングス・バースデー", "King's Birthday",
            "ミートパイ", "meat pie", "store",
            "ビーフのパイ生地包み。コンビニの定番"),
    Holiday("waitangi-nz", "02-06", "ニュージーランド", "🇳🇿", "ワイタンギ・デー", "Waitangi Day",
            "パブロバ", "pavlova", "home",
            "メレンゲのケーキ。生クリームと旬の果物で"),
    Holiday("losar-tibet", "02-28", "チベット", "🏔️", "ロサル", "Losar",
            "モモ", "momo", "specialty",
            "羊肉を包んだ蒸し餃子。チベット新年に"),
    Holiday("3kingscake", "01-06", "フランス", "🇫🇷", "公現祭", "Épiphanie",
            "ガレット・デ・ロワ", "galette des rois", "store",
            "アーモンドクリームのパイ生地ケーキ。小さな陶器人形入り"),
    Holiday("walt-bday-it", "06-02", "イタリア", "🇮🇹", "共和国記念日", "Festa della Repubblica",
            "ティラミス", "tiramisù", "home",
            "マスカルポーネとコーヒーの定番ドルチェ"),
    Holiday("nat-day-be", "07-21", "ベルギー", "🇧🇪", "ベルギー建国記念日", "Belgian National Day",
            "ムール貝とフリッツ", "moules-frites", "store",
            "白ワイン蒸しのムール貝にフライドポテト"),
    Holiday("nat-day-pe", "07-28", "ペルー", "🇵🇪", "独立記念日", "Fiestas Patrias",
            "セビーチェ", "ceviche", "specialty",
            "白身魚をライムで〆る冷菜"),
    Holiday("nat-day-co", "07-20", "コロンビア", "🇨🇴", "独立記念日", "Día de la Independencia",
            "アヒアコ", "ajiaco", "specialty",
            "じゃがいも 3 種と鶏のスープ"),
    Holiday("nat-day-arg", "07-09", "アルゼンチン", "🇦🇷", "独立記念日", "Día de la Independencia",
            "アサード", "asado", "specialty",
            "牛肉の炭火焼き。家族と長時間"),
    Holiday("nat-day-cl", "09-18", "チリ", "🇨🇱", "独立記念日", "Fiestas Patrias",
            "エンパナーダ", "empanada de pino", "store",
            "牛肉・玉ねぎ・オリーブを包んだ小さなパイ"),
    Holiday("oct-fr", "10-12", "スペイン", "🇪🇸", "イスパニアの日", "Fiesta Nacional de España",
            "パエリア", "paella", "specialty",
            "サフラン米と魚介の鍋料理"),
    Holiday("hari-merdeka-bn", "02-23", "ブルネイ", "🇧🇳", "建国記念日", "National Day",
            "アンブヤット", "ambuyat", "specialty",
            "サゴ椰子のでんぷんを溶いた粘りある主食"),
    Holiday("oktoberfest-ee", "02-24", "エストニア", "🇪🇪", "独立記念日", "Estonia Independence Day",
            "カマ", "kama", "home",
            "穀物粉とヨーグルトを混ぜた朝食"),
    Holiday("nat-day-pl", "11-11", "ポーランド", "🇵🇱", "独立記念日", "Independence Day",
            "ピエロギ", "pierogi", "home",
            "じゃがいもとチーズの蒸し餃子"),
    Holiday("kayako-tr", "10-29", "トルコ", "🇹🇷", "共和国宣言記念日", "Cumhuriyet Bayramı",
            "イスケンデルケバブ", "İskender kebap", "specialty",
            "薄切り羊肉、トマトソース、ヨーグルトの皿"),
)


def all_holidays() -> tuple[Holiday, ...]:
    return HOLIDAYS


def by_id(hid: str) -> Holiday | None:
    return next((h for h in HOLIDAYS if h.id == hid), None)
